### ISSUE TITLE
Can creators be followed using this sdk? 

### ISSUE THREAD

**Issue by namelessperson0** [ItsAditya-xyz/DeSo.py#15]
The endpoint for following a user is api/v0/create-follow-txn-stateless
Does this SDK support that endpoint?

**Comment by ItsAditya-xyz** [comment]
@namelessperson0 not yet actually. I am about to release a new version of the SDK that will include it (while also updating the mergin your PR of sign.py)

EDIT: Done!
### Following/Unfollowing user on DeSo
```python
from deso import Social
import json
SEEDHEX = "" # your seed hex
PUBLIC_KEY = "" # your public key
social = Social(SEEDHEX, PUBLIC_KEY)
userToFollow = "BC1YLhBLE1834FBJbQ9JU23JbPanNYMkUsdpJZrFVqNGsCe7YadYiUg"
status = social.follow(userToFollow) #you can set isUnfollow = True, if you want to unfollow
print(status) # 200 if follow was succesful
```
