### ISSUE TITLE
Burn NFT bug

### ISSUE THREAD

**Issue by firedreamgames** [ItsAditya-xyz/DeSo.py#17]
in line 329 of social.py for burn-nft 
 **`endpointURL = self.NODE_URL + "update-nft"`**
this should be updated as 
**`endpointURL = self.NODE_URL + "burn-nft"`**

**Comment by ItsAditya-xyz** [comment]
hey @firedreamgames , just deployed a new version with this change.
update the module to : https://pypi.org/project/deso/ and lmk.
thanks!
