### ISSUE TITLE
Error with call to getFollowsStateless

### ISSUE THREAD

**Issue by nborggren** [ItsAditya-xyz/DeSo.py#33]
it seems like the API has changed to get following/followers:

print(desoUser.getFollowsStateless(username = "ItsAditya", getFollowing = False).json())

AttributeError: 'User' object has no attribute 'getFollowsStateless'

**Comment by melzubeir** [comment]
It has not.

**Comment by nborggren** [comment]
fixed with update to 2.2.4 and install of hdwallet.  cheers.
