### ISSUE TITLE
blockheight API

### ISSUE THREAD

**Issue by nborggren** [ItsAditya-xyz/DeSo.py#34]
I was expecting to find but not seeing an API for returning the block at some height.  Is this available?  Kind of like what one sees here, but read into json:
https://explorer.deso.org/?query-node=https:%2F%2Fnode.deso.org&block-height=142

**Comment by melzubeir** [comment]
yeah, this is coming from an endpoint that is only available to exchanges.. 

https://docs.deso.org/for-developers/exchange-listing-api#api-v1-block

there is a major overhaul of the api endpoints coming on in the next few weeks, but i doubt this is going to be a part of it. either way, that's something for upstream to decide on

**Comment by nborggren** [comment]
thanks for the update/info
