### ISSUE TITLE
Getting this for almost all posts requests since around version 2.0.0

### ISSUE THREAD

**Issue by nheffelman** [ItsAditya-xyz/DeSo.py#39]
{'error': 'HandleHotFeedPageRequest: Problem parsing request body: json: cannot unmarshal array into Go struct field HotFeedPageRequest.ReaderPublicKeyBase58Check of type string'}

**Comment by ItsAditya-xyz** [comment]
can you show me your code? make sure to read the sample code in github readme

**Comment by nheffelman** [comment]
Hey itsaditya, I fixed it by changing this in the deso/posts.py 

class Posts: 
     def __init__(self, nodeURL="https://node.deso.org/api/v0/"): 
         self.NODE_URL = nodeURL 
         self.readerPublicKey="BC1YLgk64us61PUyJ7iTEkV4y2GqpHSi8ejWJRnZwsX6XRTZSfUKsop",

To 
 self.readerPublicKey=None,

-------------------------------------------------

This was my code in the app

userposts = deso.Posts().getPostsStateless(numToFetch=5)

----------------------------------------------------
I haven't tried to see if I can just change it to None or another reader in my own code.

**Comment by ItsAditya-xyz** [comment]
this is fixed now btw
